load("@elk//:elk.bzl", "elk_packages", "uv_packages")
load(":uv.lock.toml", lock = "value")

# Custom platforms select, instead of the default get_reindeer_platforms().
# The string values must match the keys in platform_tags.
#
# Possibilities here are basically endless -- you could have 7 different versions of linux-x86_64
# for different python distributions, or target many versions of macOS all with python 3.11.
# Configure as many platforms as you actually need.
MY_PLATFORMS = select({
    "DEFAULT": None,
    "prelude//os:linux": select({
        "DEFAULT": None,
        "prelude//cpu:x86_64": "linux-x86_64",
    }),
})

elk_packages(
    packages = uv_packages(lock),
    platforms = MY_PLATFORMS,
    platform_tags = {
        "linux-x86_64": ["py3-none-any"],
    },
)

python_binary(
    name = "main",
    main = "main.py",
    deps = [
        # keep sorted
        ":cowsay",
    ],
)
