python_binary(
    name = "main",
    main = "main.py",
    deps = [
        # keep sorted
        "//example/uv:colorama",
        "//example/uv:cowsay",
        "//example/uv:numpy",
    ],
)

python_binary(
    name = "other",
    main = "other.py",
    deps = [
        # keep sorted
        "//example/uv:numpy",
        "//example/uv:polars",
    ],
)
