[tool.poetry]
name = "example"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "1.26.4"
pyarrow = "16.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
