load("@elk//:elk.bzl", "elk_packages", "poetry_packages")
load(":linux-x86_64.tags.json", linux_x86_64_tags = "value")
load(":poetry.lock.toml", lock = "value")

elk_packages(
    packages = poetry_packages(lock),
    platform_tags = {
        "linux-x86_64": linux_x86_64_tags,
    },
)
