# Python version common to all platforms.
# If you want to build for a different version of python on different platforms, sorry.
# Submit a PR.
# Note that the ABI versions can be different -- you might want to use PyPy on Linux,
# but not on Mac.
[python]
version = [3, 12]
interpreter = "cp312" # CPython 3.12 compatible
cpython = true

# Platforms we want to support.
#
# These are essentially PyPi wheel selectors.
#
# The names ('linux-x86_64' etc) are mapped to Buck select({}) calls
# using platform.bzl. The wheel selectors here should match which
# operating systems / glibc versions / etc are being used when the
# select({}) statements therein evaluate to True.
#
# platform.bzl uses
#
#     load("@prelude//rust:cargo_package.bzl", "DEFAULT_PLATFORM_TEMPLATES")
#
# as the default dictionary of platform templates.
# But you can create your own by pulling that dictionary from the prelude and
# modifying `platform.bzl`.
#
# As for the attributes, they are used to generate long lists of compatible tags.
# The first matching wheel is used for each platform.

[platform.linux-x86_64]
platform = "linux"
arch = "x86_64"
abi = ["cp312", "abi3", "none"]
glibc_version = [2, 38]
manylib2014_compatible = true

[platform.linux-arm64]
platform = "linux"
arch = "arm64"
abi = ["cp312", "abi3", "none"]
glibc_version = [2, 38]
manylib2014_compatible = true

[platform.macos-x86_64]
platform = "darwin"
arch = "x86_64"
abi = ["cp312", "abi3", "none"]
macos_version = [13, 0]

[platform.macos-arm64]
platform = "darwin"
arch = "arm64"
abi = ["cp312", "abi3", "none"]
macos_version = [13, 0]

# Windows not supported yet

# Configuration for poetry (used for resolving dependencies)
[poetry]

# Configuration for generated BUCK file
[buck]
# Name of the generated file
file_name = "BUCK" # default

# Rules used for various kinds of targets. These rules don't directly correspond
# with BUCK rules - they have extra attributes such as per-platform settings.
# The intent is that you provide a set of macro definitions which resolve them
# to appropriate underlying rules suitable for your environment. (This may also
# work for Buck-like build systems such as Bazel.)

# Load the macros to which the rules above will resolve.
buckfile_imports = """
load(":platform.bzl", "platform")

# A target for aliases to resolve to on unsupported platforms
filegroup(name = "null", srcs = [])
"""

# Need a wrapper for alias that will evaluate the `platforms` attribute.
alias = "platform.alias"
prebuilt_python_library = "prebuilt_python_library"
python_library = "python_library"

# Banner comment for the generated BUCK File.
# Turn off syntax highlighting in vim because it's just too slow
generated_file_header = """
##
## This file is automatically @generated by elk and should not be changed by hand.
##
## See README.md for directions on how to update this.
##
"""
